// This .js file is auto-generated by `createCesium()` from VeRoViz
// Display nodes for cesium application

function displayNodes() {
    var pin = new Array;
    pin[0] = viewer.entities.add({
        name : '0',
        parent : nodePins,
        description : 'Depot',
        position : Cesium.Cartesian3.fromDegrees(-78.787034, 43.001742),
        billboard : {
            image : pinBuilder.fromText('0', Cesium.Color.RED, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[1] = viewer.entities.add({
        name : '1',
        parent : nodePins,
        description : 'Cust1',
        position : Cesium.Cartesian3.fromDegrees(-78.816851, 43.015717),
        billboard : {
            image : pinBuilder.fromText('1', Cesium.Color.GREEN, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[2] = viewer.entities.add({
        name : '2',
        parent : nodePins,
        description : 'Cust2',
        position : Cesium.Cartesian3.fromDegrees(-78.791655, 43.031084),
        billboard : {
            image : pinBuilder.fromText('2', Cesium.Color.GREEN, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[3] = viewer.entities.add({
        name : '3',
        parent : nodePins,
        description : 'Cust3',
        position : Cesium.Cartesian3.fromDegrees(-78.749357, 43.010989),
        billboard : {
            image : pinBuilder.fromText('3', Cesium.Color.GREEN, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

}