// This .js file is auto-generated by `createCesium()` from VeRoViz
// The configs for cesium application go to here

function setConfigs() {
    viewer.camera.flyTo({
        destination: Cesium.Rectangle.fromDegrees(-78.787765, 42.988959, -78.767274, 43.009319) 
    });
    viewer.clock.currentTime = Cesium.JulianDate.addSeconds('2020-10-23T08:00:00Z', 0, new Cesium.JulianDate());
    allIDs = [
        'o-blue box-/veroviz/models/box_blue.gltf-stationary', 
        'o-yellow box-/veroviz/models/box_yellow.gltf-stationary', 
        'o-red rectangle-/veroviz/models/rectangle_red.gltf-stationary', 
        'o-blue rectangle-/veroviz/models/rectangle_blue.gltf-stationary', 
        'o-green rectangle-/veroviz/models/rectangle_green.gltf-stationary', 
        'o-white rectangle-/veroviz/models/rectangle_white.gltf-stationary', 
        'o-black rectangle-/veroviz/models/rectangle_black.gltf-stationary', 
        'o-red wedge-/veroviz/models/wedge_red.gltf-stationary', 
        'o-blue wedge-/veroviz/models/wedge_blue.gltf-stationary', 
        'o-green wedge-/veroviz/models/wedge_green.gltf-stationary', 
        'o-white wedge-/veroviz/models/wedge_white.gltf-stationary', 
        'o-black wedge-/veroviz/models/wedge_black.gltf-stationary', 
        'o-blue car-/veroviz/models/car_blue.gltf-stationary', 
        'o-green car-/veroviz/models/car_green.gltf-stationary', 
        'o-red car-/veroviz/models/car_red.gltf-stationary', 
        'o-drone with package-/veroviz/models/drone_package.gltf-stationary', 
        'o-drone-/veroviz/models/drone.gltf-stationary', 
        'o-UB airplane-/veroviz/models/ub_airplane.gltf-stationary', 
        'o-UB truck-/veroviz/models/ub_truck.gltf-stationary'    
    ];
    orientationIDs = [
    ];
    czmlRouteFile = '/veroviz/view_models/routes.czml';
    runRoutes(czmlRouteFile, allIDs, orientationIDs);
objectInfo['blue box-/veroviz/models/box_blue.gltf'] = {
    label : 'blue box (/veroviz/models/box_blue.gltf)', 
    childModels : ['o-blue box-/veroviz/models/box_blue.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['yellow box-/veroviz/models/box_yellow.gltf'] = {
    label : 'yellow box (/veroviz/models/box_yellow.gltf)', 
    childModels : ['o-yellow box-/veroviz/models/box_yellow.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['red rectangle-/veroviz/models/rectangle_red.gltf'] = {
    label : 'red rectangle (/veroviz/models/rectangle_red.gltf)', 
    childModels : ['o-red rectangle-/veroviz/models/rectangle_red.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['blue rectangle-/veroviz/models/rectangle_blue.gltf'] = {
    label : 'blue rectangle (/veroviz/models/rectangle_blue.gltf)', 
    childModels : ['o-blue rectangle-/veroviz/models/rectangle_blue.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['green rectangle-/veroviz/models/rectangle_green.gltf'] = {
    label : 'green rectangle (/veroviz/models/rectangle_green.gltf)', 
    childModels : ['o-green rectangle-/veroviz/models/rectangle_green.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['white rectangle-/veroviz/models/rectangle_white.gltf'] = {
    label : 'white rectangle (/veroviz/models/rectangle_white.gltf)', 
    childModels : ['o-white rectangle-/veroviz/models/rectangle_white.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['black rectangle-/veroviz/models/rectangle_black.gltf'] = {
    label : 'black rectangle (/veroviz/models/rectangle_black.gltf)', 
    childModels : ['o-black rectangle-/veroviz/models/rectangle_black.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['red wedge-/veroviz/models/wedge_red.gltf'] = {
    label : 'red wedge (/veroviz/models/wedge_red.gltf)', 
    childModels : ['o-red wedge-/veroviz/models/wedge_red.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['blue wedge-/veroviz/models/wedge_blue.gltf'] = {
    label : 'blue wedge (/veroviz/models/wedge_blue.gltf)', 
    childModels : ['o-blue wedge-/veroviz/models/wedge_blue.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['green wedge-/veroviz/models/wedge_green.gltf'] = {
    label : 'green wedge (/veroviz/models/wedge_green.gltf)', 
    childModels : ['o-green wedge-/veroviz/models/wedge_green.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['white wedge-/veroviz/models/wedge_white.gltf'] = {
    label : 'white wedge (/veroviz/models/wedge_white.gltf)', 
    childModels : ['o-white wedge-/veroviz/models/wedge_white.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['black wedge-/veroviz/models/wedge_black.gltf'] = {
    label : 'black wedge (/veroviz/models/wedge_black.gltf)', 
    childModels : ['o-black wedge-/veroviz/models/wedge_black.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['blue car-/veroviz/models/car_blue.gltf'] = {
    label : 'blue car (/veroviz/models/car_blue.gltf)', 
    childModels : ['o-blue car-/veroviz/models/car_blue.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['green car-/veroviz/models/car_green.gltf'] = {
    label : 'green car (/veroviz/models/car_green.gltf)', 
    childModels : ['o-green car-/veroviz/models/car_green.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['red car-/veroviz/models/car_red.gltf'] = {
    label : 'red car (/veroviz/models/car_red.gltf)', 
    childModels : ['o-red car-/veroviz/models/car_red.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['drone with package-/veroviz/models/drone_package.gltf'] = {
    label : 'drone with package (/veroviz/models/drone_package.gltf)', 
    childModels : ['o-drone with package-/veroviz/models/drone_package.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['drone-/veroviz/models/drone.gltf'] = {
    label : 'drone (/veroviz/models/drone.gltf)', 
    childModels : ['o-drone-/veroviz/models/drone.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['UB airplane-/veroviz/models/ub_airplane.gltf'] = {
    label : 'UB airplane (/veroviz/models/ub_airplane.gltf)', 
    childModels : ['o-UB airplane-/veroviz/models/ub_airplane.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['UB truck-/veroviz/models/ub_truck.gltf'] = {
    label : 'UB truck (/veroviz/models/ub_truck.gltf)', 
    childModels : ['o-UB truck-/veroviz/models/ub_truck.gltf-stationary'],
    scale : 100, 
    minPxSize : 75 
}; 
    registerObjects(objectInfo); 
}